"""flight route migration

Revision ID: 108a47b61065
Revises: d296b588d207
Create Date: 2023-06-26 17:50:25.406016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108a47b61065'
down_revision = 'd296b588d207'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
