"""init data

Revision ID: 342a88361cfb
Revises: 3da22db443bd
Create Date: 2023-06-27 19:55:15.531918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342a88361cfb'
down_revision = '3da22db443bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    INSERT INTO 
        airline (name, url, require_subscription)
    VALUES 
        ('KLM', 'https://www.klm.com', false),
        ('Multiple Airlines', 'https://www.multipleairlines.com', false),
        ('American Airlines', 'https://www.aa.com', false),
        ('Air France', 'https://www.airfrance.com', false),
        ('Lufthansa', 'https://www.lufthansa.com', false),
        ('Air Canada', 'https://www.aircanada.com', false),
        ('United Airlines', 'https://www.united.com', false),
        ('British Airways', 'https://www.britishairways.com', true),
        ('Qatar Airways', 'https://www.qatarairways.com', true),
        ('Finnair', 'https://www.finnair.com', true),
        ('Emirates', 'https://www.emirates.com', true),
        ('SAUDIA', 'https://www.saudia.com', true),
        ('SWISS', 'https://www.swiss.com', true),
        ('Finnair, American Airlines', 'https://www.finnair-aa.com', true),
        ('LOT', 'https://www.lot.com', true),
        ('Aeroflot', 'https://www.aeroflot.ru', true),
        ('Turkish Airlines', 'https://www.turkishairlines.com', true),
        ('Lufthansa, Egypt Air', 'https://www.lufthansa-egyptair.com', true),
        ('TAP AIR PORTUGAL', 'https://www.flytap.com', true);
    """)
    op.execute("""
    INSERT INTO 
        flight_route (code, name, require_subscription)
    VALUES 
        ('NYC', 'NUEVA YORK', false),
        ('PAR', 'PARIS', false),
        ('RUH', 'RIAD ARABIA SAUDI', false),
        ('SVO', 'MOSCU', true);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
