"""airline migration

Revision ID: d296b588d207
Revises: 2cf0bcbd5605
Create Date: 2023-06-26 17:50:05.471118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd296b588d207'
down_revision = '2cf0bcbd5605'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
